<a href="https://colab.research.google.com/github/Asinjoji/Casestudy_Data_Acquisition_Asin/blob/main/Case_Study_Asin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#TASK 1
filepath='/content/population.csv'
df=pd.read_csv(filepath)
df

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [ ]:
df.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
df.shape

(25, 2)

In [3]:
df.dtypes

country       object
population     int64
dtype: object

In [4]:
#TASK 2
filepath='/content/gdp.xlsx'
df=pd.read_excel(filepath)
print(df.dtypes)

Country    object
GDP         int64
dtype: object

In [ ]:
df.dtypes

Country    object
GDP         int64
dtype: object

In [5]:
#TASK 3
filepath='/content/internet_users.json'
df=pd.read_json(filepath)
df

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [6]:
#TASK 4
filepath='/content/literacy_rate.xml'
df=pd.read_xml(filepath)
df

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

PART B

In [7]:
#TASK 5
population = pd.read_csv('population.csv')
gdp = pd.read_excel('gdp.xlsx')
internet_users = pd.read_json('internet_users.json')
literacy = pd.read_xml('literacy_rate.xml')

In [8]:
print("POPULATION DATASET")
print("Rows:", population.shape[0])
print("Columns:", population.shape[1])
print("Column names:", population.columns.tolist())
print("Data types:\n", population.dtypes)
print("Missing values:\n", population.isnull().sum())
print("Duplicate records:", population.duplicated().sum())

POPULATION DATASET
Rows: 25
Columns: 2
Column names: ['country', 'population']
Data types:
 country       object
population     int64
dtype: object
Missing values:
 country       0
population    0
dtype: int64
Duplicate records: 0

In [9]:
print("\nGDP DATASET")
print("Rows:", gdp.shape[0])
print("Columns:", gdp.shape[1])
print("Column names:", gdp.columns.tolist())
print("Data types:\n", gdp.dtypes)
print("Missing values:\n", gdp.isnull().sum())
print("Duplicate records:", gdp.duplicated().sum())

GDP DATASET
Rows: 25
Columns: 2
Column names: ['Country', 'GDP']
Data types:
 Country    object
GDP         int64
dtype: object
Missing values:
 Country    0
GDP        0
dtype: int64
Duplicate records: 0

In [ ]:
print("\nINTERNET USERS DATASET")
print("Rows:", internet_users.shape[0])
print("Columns:", internet_users.shape[1])
print("Column names:", internet_users.columns.tolist())
print("Data types:\n", internet_users.dtypes)
print("Missing values:\n", internet_users.isnull().sum())
print("Duplicate records:", internet_users.duplicated().sum())

INTERNET USERS DATASET
Rows: 25
Columns: 2
Column names: ['country', 'internet_users']
Data types:
 country           object
internet_users     int64
dtype: object
Missing values:
 country           0
internet_users    0
dtype: int64
Duplicate records: 0

In [ ]:
print("\nLITERACY RATE DATASET")
print("Rows:", literacy.shape[0])
print("Columns:", literacy.shape[1])
print("Column names:", literacy.columns.tolist())
print("Data types:\n", literacy.dtypes)
print("Missing values:\n", literacy.isnull().sum())
print("Duplicate records:", literacy.duplicated().sum())

LITERACY RATE DATASET
Rows: 25
Columns: 2
Column names: ['name', 'literacy_rate']
Data types:
 name              object
literacy_rate    float64
dtype: object
Missing values:
 name             0
literacy_rate    0
dtype: int64
Duplicate records: 0

PART C

In [ ]:
#TASK 6
gdp = gdp.rename(columns={'Country': 'country'})
literacy = literacy.rename(columns={'name': 'country'})

print("Population:", population.columns.tolist())
print("GDP:", gdp.columns.tolist())
print("Internet Users:", internet_users.columns.tolist())
print("Literacy rate:", literacy.columns.tolist())

Population: ['country', 'population']
GDP: ['country', 'GDP']
Internet Users: ['country', 'internet_users']
Literacy rate: ['country', 'literacy_rate']

In [ ]:
#TASK 7
population['country'] = population['country'].astype('string')
gdp['country'] = gdp['country'].astype('string')
internet_users['country'] = internet_users['country'].astype('string')
literacy['country'] = literacy['country'].astype('string')


population['population'] = pd.to_numeric(population['population'], errors='coerce').astype('Int64')
gdp['GDP'] = pd.to_numeric(gdp['GDP'], errors='coerce').astype('Int64')
internet_users['internet_users'] = pd.to_numeric(internet_users['internet_users'], errors='coerce').astype('Int64')
literacy['literacy_rate'] = pd.to_numeric(literacy['literacy_rate'], errors='coerce').astype('float64')


print("Population Data Types:\n", population.dtypes, "\n")
print("GDP Data Types:\n", gdp.dtypes, "\n")
print("Internet Users Data Types:\n", internet_users.dtypes, "\n")
print("Literacy Rate Data Types:\n", literacy.dtypes)

Population Data Types:
 country       string[python]
population             Int64
dtype: object

GDP Data Types:
 country    string[python]
GDP                 Int64
dtype: object

Internet Users Data Types:
 country           string[python]
internet_users             Int64
dtype: object

Literacy Rate Data Types:
 country          string[python]
literacy_rate           float64
dtype: object

In [ ]:
#TASK 8
df1 = pd.merge(population, gdp, on='country', how='outer')
df2 = pd.merge(df1, internet_users, on='country', how='outer')
final_df = pd.merge(df2, literacy, on='country', how='outer')

final_df

           country  population       GDP  internet_users  literacy_rate
0        Argentina    45195774    640000        41000000           99.1
1        Australia    25687041   1880000        24000000           99.0
2           Brazil   212559417   2330000       181000000           93.2
3           Canada    38005238   2250000        36000000           99.0
4            China  1411778724  19230000      1080000000           97.2
5           France    65273511   3211000        62000000           99.0
6          Germany    83240525   4744000        79000000           99.0
7            India  1380004385   4187000       850000000           77.7
8        Indonesia   273523615   1500000       212000000           96.0
9            Italy    60461826   2420000        56000000           99.0
10           Japan   125836021   4180000       118000000           99.0
11          Mexico   128932753   1810000       102000000           95.4
12     Netherlands    17441139   1150000        17000000           99.0
13          Norway     5421241    580000         5300000          100.0
14          Russia   145934462   2200000       125000000           99.7
15    Saudi Arabia    34813871   1100000        34000000           97.3
16       Singapore     5850342    530000         5600000           97.5
17    South Africa    59308690    410000        43000000           95.0
18     South Korea    51780579   1800000        50000000           98.8
19           Spain    46754778   1710000        44000000           98.6
20          Sweden    10353442    650000        10100000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Turkey    84339067   1350000        69000000           96.7
23  United Kingdom    67886011   3839000        66000000           99.0
24   United States   331002651  30500000       312000000           99.0

In [ ]:
#TASK 9
# 1. Internet Penetration (%)
final_df['Internet Penetration (%)'] = round((final_df['internet_users'] / final_df['population']) * 100, 2)

# 2. GDP Per Capita
final_df['GDP Per Capita'] = round(final_df['GDP'] / final_df['population'], 2)

final_df

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Argentina,45195774,640000,41000000,99.1,90.72,0.01
1,Australia,25687041,1880000,24000000,99.0,93.43,0.07
2,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
3,Canada,38005238,2250000,36000000,99.0,94.72,0.06
4,China,1411778724,19230000,1080000000,97.2,76.5,0.01
5,France,65273511,3211000,62000000,99.0,94.98,0.05
6,Germany,83240525,4744000,79000000,99.0,94.91,0.06
7,India,1380004385,4187000,850000000,77.7,61.59,0.0
8,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
9,Italy,60461826,2420000,56000000,99.0,92.62,0.04
10,Japan,125836021,4180000,118000000,99.0,93.77,0.03
11,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
12,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
13,Norway,5421241,580000,5300000,100.0,97.76,0.11
14,Russia,145934462,2200000,125000000,99.7,85.65,0.02
15,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
16,Singapore,5850342,530000,5600000,97.5,95.72,0.09
17,South Africa,59308690,410000,43000000,95.0,72.5,0.01
18,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
19,Spain,46754778,1710000,44000000,98.6,94.11,0.04
20,Sweden,10353442,650000,10100000,99.0,97.55,0.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
23,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
24,United States,331002651,30500000,312000000,99.0,94.26,0.09

PART D

In [ ]:
#TASK 10
import sqlite3

conn = sqlite3.connect('country_data.db')

final_df.to_sql('country_statistics', conn, if_exists='replace', index=False)

25

In [15]:
#TASK 11

query = "SELECT * FROM country_statistics"
verification_df = pd.read_sql(query, conn)

verification_df

           country  population       GDP  internet_users  literacy_rate
0        Argentina    45195774    640000        41000000           99.1
1        Australia    25687041   1880000        24000000           99.0
2           Brazil   212559417   2330000       181000000           93.2
3           Canada    38005238   2250000        36000000           99.0
4            China  1411778724  19230000      1080000000           97.2
5           France    65273511   3211000        62000000           99.0
6          Germany    83240525   4744000        79000000           99.0
7            India  1380004385   4187000       850000000           77.7
8        Indonesia   273523615   1500000       212000000           96.0
9            Italy    60461826   2420000        56000000           99.0
10           Japan   125836021   4180000       118000000           99.0
11          Mexico   128932753   1810000       102000000           95.4
12     Netherlands    17441139   1150000        17000000           99.0
13          Norway     5421241    580000         5300000          100.0
14          Russia   145934462   2200000       125000000           99.7
15    Saudi Arabia    34813871   1100000        34000000           97.3
16       Singapore     5850342    530000         5600000           97.5
17    South Africa    59308690    410000        43000000           95.0
18     South Korea    51780579   1800000        50000000           98.8
19           Spain    46754778   1710000        44000000           98.6
20          Sweden    10353442    650000        10100000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Turkey    84339067   1350000        69000000           96.7
23  United Kingdom    67886011   3839000        66000000           99.0
24   United States   331002651  30500000       312000000           99.0

PART E

In [17]:
# 1 List the Top 5 countries by GDP.
top_5_gdp = final_df.nlargest(5, 'GDP')[['country', 'GDP']]
display(top_5_gdp)

          country       GDP
24  United States  30500000
4           China  19230000
6         Germany   4744000
7           India   4187000
10          Japan   4180000

In [18]:
# 2 List the Top 5 countries by population.
top_5_population = final_df.nlargest(5, 'population')[['country', 'population']]
display(top_5_population)

          country  population
4           China  1411778724
7           India  1380004385
24  United States   331002651
8       Indonesia   273523615
2          Brazil   212559417

In [19]:
# 3 Calculate the average literacy rate.
avg_literacy = final_df['literacy_rate'].mean()
print(f"Average Literacy Rate: {avg_literacy:.2f}%")

Average Literacy Rate: 97.25%

In [20]:
# 4 List all countries having a literacy rate greater than 90%.
literacy_above_90 = final_df[final_df['literacy_rate'] > 90][['country', 'literacy_rate']]
display(literacy_above_90)

           country  literacy_rate
0        Argentina           99.1
1        Australia           99.0
2           Brazil           93.2
3           Canada           99.0
4            China           97.2
5           France           99.0
6          Germany           99.0
8        Indonesia           96.0
9            Italy           99.0
10           Japan           99.0
11          Mexico           95.4
12     Netherlands           99.0
13          Norway          100.0
14          Russia           99.7
15    Saudi Arabia           97.3
16       Singapore           97.5
17    South Africa           95.0
18     South Korea           98.8
19           Spain           98.6
20          Sweden           99.0
21     Switzerland           99.0
22          Turkey           96.7
23  United Kingdom           99.0
24   United States           99.0

In [25]:
# 5 List all countries having an internet penetration greater than 70%.
final_df['Internet Penetration (%)'] = round((final_df['internet_users'] / final_df['population']) * 100, 2)
internet_penetration_above_70 = final_df[final_df['Internet Penetration (%)'] > 70][['country', 'Internet Penetration (%)']]
display(internet_penetration_above_70)

           country  Internet Penetration (%)
0        Argentina                     90.72
1        Australia                     93.43
2           Brazil                     85.15
3           Canada                     94.72
4            China                     76.50
5           France                     94.98
6          Germany                     94.91
8        Indonesia                     77.51
9            Italy                     92.62
10           Japan                     93.77
11          Mexico                     79.11
12     Netherlands                     97.47
13          Norway                     97.76
14          Russia                     85.65
15    Saudi Arabia                     97.66
16       Singapore                     95.72
17    South Africa                     72.50
18     South Korea                     96.56
19           Spain                     94.11
20          Sweden                     97.55
21     Switzerland                     98.21
22          Turkey                     81.81
23  United Kingdom                     97.22
24   United States                     94.26

In [28]:
# 6 List the Top 5 countries by GDP per capita.
final_df['GDP Per Capita'] = round(final_df['GDP'] / final_df['population'], 2)
top_5_gdp_per_capita = final_df.nlargest(5, 'GDP Per Capita')[['country', 'GDP Per Capita']]
display(top_5_gdp_per_capita)

          country  GDP Per Capita
13         Norway            0.11
21    Switzerland            0.11
16      Singapore            0.09
24  United States            0.09
1       Australia            0.07

In [29]:
# 7 Calculate the total population represented in the dataset.
total_population = final_df['population'].sum()
print(f"Total Population: {total_population:,}")

Total Population: 4,720,039,725

In [30]:
# 8 Calculate the average internet penetration across all countries.
avg_internet_penetration = final_df['Internet Penetration (%)'].mean()
print(f"Average Internet Penetration: {avg_internet_penetration:.2f}%")

Average Internet Penetration: 89.66%

In [31]:
# 9 Identify the country having the highest number of internet users.
highest_internet_users = final_df.nlargest(1, 'internet_users')[['country', 'internet_users']]
display(highest_internet_users)

  country  internet_users
4   China      1080000000

In [32]:
# 10 Find the correlation between Literacy Rate and Internet Penetration.
correlation = final_df['literacy_rate'].corr(final_df['Internet Penetration (%)'])
print(f"Correlation: {correlation:.4f}")

Correlation: 0.7728

PART F

In [33]:
# 11 Display the Top 5 countries by GDP.
query_11 = """SELECT country, GDP FROM country_statistics ORDER BY GDP DESC LIMIT 5"""
df_11 = pd.read_sql(query_11, conn)
display(df_11)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [34]:
# 12 Find the average literacy rate.
query_12 = """SELECT AVG(literacy_rate) AS average_literacy_rate FROM country_statistics"""
df_12 = pd.read_sql(query_12, conn)
display(df_12)

   average_literacy_rate
0                 97.248

In [35]:
# 13 Display all countries having literacy rate above 90%.
query_13 = """SELECT country, literacy_rate FROM country_statistics WHERE literacy_rate > 90"""
df_13 = pd.read_sql(query_13, conn)
display(df_13)

           country  literacy_rate
0        Argentina           99.1
1        Australia           99.0
2           Brazil           93.2
3           Canada           99.0
4            China           97.2
5           France           99.0
6          Germany           99.0
7        Indonesia           96.0
8            Italy           99.0
9            Japan           99.0
10          Mexico           95.4
11     Netherlands           99.0
12          Norway          100.0
13          Russia           99.7
14    Saudi Arabia           97.3
15       Singapore           97.5
16    South Africa           95.0
17     South Korea           98.8
18           Spain           98.6
19          Sweden           99.0
20     Switzerland           99.0
21          Turkey           96.7
22  United Kingdom           99.0
23   United States           99.0

In [37]:
# 14 Find the Top 5 countries with the highest internet penetration.
final_df.to_sql('country_statistics', conn, if_exists='replace', index=False)

query_14 = """SELECT country, `Internet Penetration (%)` FROM country_statistics ORDER BY `Internet Penetration (%)` DESC LIMIT 5"""
df_14 = pd.read_sql(query_14, conn)
display(df_14)

        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [38]:
# 15 Calculate the total population.
query_15 = """SELECT SUM(population) AS total_population FROM country_statistics"""
df_15 = pd.read_sql(query_15, conn)
display(df_15)

   total_population
0        4720039725

In [39]:
# 16 Find the country with the highest GDP per capita.
query_16 = """SELECT country, `GDP Per Capita` FROM country_statistics ORDER BY `GDP Per Capita` DESC LIMIT 1"""
df_16 = pd.read_sql(query_16, conn)
display(df_16)

  country  GDP Per Capita
0  Norway            0.11

In [40]:
# 17 Export the final merged dataset as a CSV file.
final_df.to_csv('final_merged_dataset.csv', index=False)
print("Successfully exported final_merged_dataset.csv")

Successfully exported final_merged_dataset.csv

In [41]:
# 18 Sort the dataset in descending order of GDP per Capita and display the Top 10 countries.
top_10_gdp_per_capita = final_df.sort_values(by='GDP Per Capita', ascending=False).head(10)
display(top_10_gdp_per_capita)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
13,Norway,5421241,580000,5300000,100.0,97.76,0.11
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
24,United States,331002651,30500000,312000000,99.0,94.26,0.09
16,Singapore,5850342,530000,5600000,97.5,95.72,0.09
12,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
1,Australia,25687041,1880000,24000000,99.0,93.43,0.07
6,Germany,83240525,4744000,79000000,99.0,94.91,0.06
20,Sweden,10353442,650000,10100000,99.0,97.55,0.06
3,Canada,38005238,2250000,36000000,99.0,94.72,0.06
23,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06